### ISSUE TITLE
关于思路

### ISSUE THREAD

**Issue by zack-zk** [zack-zk/zack-zk.github.io#10]
换了mac后，一系列windows的操作惯性病，连vm创建虚机后，为了上网，把虚机的第一块网卡设置为了nat；虽然可以上网了，但本地一直无法ssh到对应虚机，此时百度很长时间，装vmtools、设置共享等研究半天，最后发现新添加一张网卡，然后设置该网卡本地only模式，很简单就解决了问题。。。真是思路决定出路。

**Comment by kaizamm** [comment]
DNS 及gateway的配置请参考    /Library/Preferences/VMware Fusion/vmnet8
